name: ✉️ Send Email

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setting Node & Caching Yarn Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Node Packages
        run: yarn install --frozen-lockfile
      - name: Check data & Send Email!
        env:
            SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: yarn start