name: ✉️ Send Email

on:
  push:
    branches:
      - master
  schedule:
    - cron: '50 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - uses: Set up python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
    
    - name: Install python package
      run: pip install -r requirements.txt

    - name: Check data & Send Email!
      env:
        SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
        RECV_EMAIL: ${{ secrets.RECV_EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: | 
        python ./main.py 
