name: 🚀 Run Script

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16.x"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: ⚙️ Setting Node & Caching Yarn Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: 🚀 Install Node Packages
        run: yarn install --frozen-lockfile
      - name: Run Script
        env:
          SEND_EMAIL: ${{ secrets.SEND_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NOTION_US_DATABASE_ID: ${{ secrets.NOTION_US_DATABASE_ID }}
          NOTION_KR_DATABAS⚙️E_ID: ${{ secrets.NOTION_KR_DATABASE_ID }}
          NOTION_USER_KEY: ${{ secrets.NOTION_USER_KEY }}
        run: yarn start
